import { config } from "../config.js";
import { structuredCompletion } from "./client.js";

/**
 * End-of-call recap. Given the full transcript, produce a structured summary
 * suitable for writing onto the customer's CRM record. Returns null when AI is
 * disabled or the transcript is empty.
 */

const RECAP_SYSTEM = `You are a post-call analyst for "We Insure Things", a US insurance brokerage. You read a completed sales call transcript and extract a concise, factual recap for the customer's CRM record.

Rules:
- Summarize only what was actually said. Do not invent prices, coverage, or commitments.
- "summary" is 2-4 sentences an agent could skim before the next call.
- "outcome" is your best read of where the call landed.
- Leave arrays empty and "followUpDate" as "" when nothing applies.
- "followUpDate" should be an ISO date (YYYY-MM-DD) only if a specific follow-up time was agreed; otherwise "".`;

const RECAP_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    summary: { type: "string" },
    outcome: {
      type: "string",
      enum: [
        "sale",
        "follow_up",
        "callback",
        "quote_requested",
        "not_interested",
        "no_answer",
        "other",
      ],
    },
    productsDiscussed: { type: "array", items: { type: "string" } },
    objections: { type: "array", items: { type: "string" } },
    nextSteps: { type: "array", items: { type: "string" } },
    followUpDate: { type: "string" },
    customerSentiment: {
      type: "string",
      enum: ["positive", "neutral", "negative"],
    },
  },
  required: [
    "summary",
    "outcome",
    "productsDiscussed",
    "objections",
    "nextSteps",
    "followUpDate",
    "customerSentiment",
  ],
};

/**
 * @param {string} fullTranscript labelled "Agent:/Customer:" lines
 * @returns {Promise<object|null>} structured recap
 */
export async function generateRecap(fullTranscript) {
  if (!fullTranscript?.trim()) return null;

  return structuredCompletion({
    model: config.anthropic.model,
    system: RECAP_SYSTEM,
    user: `Completed call transcript:\n\n${fullTranscript}\n\nExtract the recap.`,
    schema: RECAP_SCHEMA,
    schemaName: "call_recap",
    effort: "medium",
    maxTokens: 1500,
  });
}

/**
 * Render a structured recap as a plain-text CRM note body + a subject line.
 * Kept separate from generation so it can be unit-tested without the API.
 */
export function formatRecapNote(recap, { from, to, durationSec } = {}) {
  if (!recap) return null;

  const lines = [];
  lines.push(recap.summary || "");
  lines.push("");
  lines.push(`Outcome: ${prettyOutcome(recap.outcome)}`);
  lines.push(`Customer sentiment: ${recap.customerSentiment || "unknown"}`);

  if (recap.productsDiscussed?.length) {
    lines.push(`Products discussed: ${recap.productsDiscussed.join(", ")}`);
  }
  if (recap.objections?.length) {
    lines.push("Objections:");
    for (const o of recap.objections) lines.push(`  • ${o}`);
  }
  if (recap.nextSteps?.length) {
    lines.push("Next steps:");
    for (const s of recap.nextSteps) lines.push(`  • ${s}`);
  }
  if (recap.followUpDate) lines.push(`Follow-up date: ${recap.followUpDate}`);

  const meta = [];
  if (from) meta.push(`from ${from}`);
  if (to) meta.push(`to ${to}`);
  if (durationSec != null) meta.push(`${durationSec}s`);
  if (meta.length) {
    lines.push("");
    lines.push(`Call ${meta.join(" / ")}.`);
  }
  lines.push("");
  lines.push("— Auto-generated by WIT Connect AI recap");

  return {
    subject: `Call recap — ${prettyOutcome(recap.outcome)}`,
    description: lines.join("\n"),
  };
}

function prettyOutcome(outcome) {
  if (!outcome) return "Other";
  return outcome
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
